 create table Category (
       id integer generated by default as identity,
        is_active boolean,
        description varchar(255),
        image_Url varchar(255),
        name varchar(255),
        primary key (id)
    )